### ISSUE TITLE
Subpages

### ISSUE THREAD

**Issue by badmadrabbit** [Nomadwiki/Nomadwiki#3]
(From http://nomadwiki.org/en/Tiny_Guide_for_the_Vegan_Traveler)

"I'd like to publish the chapters as subpages of this page. I need you to activate subpages. The normal way to enable subpages for a given namespace is to edit the LocalSettings.php and insert the following: $wgNamespacesWithSubpages[NS_MAIN] = true;

In the meanwhile I publish the chapters of the guide as separated articles. "

**Comment by guaka** [comment]
done!

I also added a template and a category for it

let me know if you need anything else!
