### ISSUE TITLE
nomadwiki's doppelganger 

### ISSUE THREAD

**Issue by rdoc101** [Nomadwiki/Nomadwiki#6]
Well the push to turn everything into a startup has resulted in someone creating nomadwiki.net :
https://www.reddit.com/r/digitalnomad/comments/3a0hgs/aspiring_nomads_know_your_options_in_a_big_world/

**Comment by simison** [comment]
Oh well. At least we have other important Nomadwiki domains (not sure why we didn't have this one) and social media handles.

**Comment by guaka** [comment]
Created issue here: https://github.com/digitalnomads/digitalnomads.github.io/issues/4
